export const LANGUAGES = [
    'English', 
    'Spanish', 
    'French', 
    'Portuguese',
    'Indonesian',
    'Japanese',
    'Sasak',
    'A-Pucikwar',
    'Akawaio',
    'Angaité',
    'Aruamu',
    'Aari',
    'Ake',
    'Angal',
    'Aruek',
    'Aasáx',
    'Akebu',
    'Angal Enen',
    'Aruop',
    'Abadi',
    'Akei',
    'Angal Heneng',
    'Arutani',
    'Abai Sungai',
    'Akeu',
    'Angika',
    'As',
    'Abanyom',
    'Akha',
    'Angkamuthi',
    'Asa’a',
    'Abau',
    'Akhvakh',
    'Angloromani',
    'Asaba',
    'Abaza',
    'Aklanon',
    'Angolar',
    'Asaro’o',
    'Abé',
    'Akolet',
    'Angor',
    'Asháninka',
    'Abenaki',
    'Akoose',
    'Angoram',
    'Ashe',
    'Akoye',
    'Anguthimri',
    'Ashéninka',
    'Abidji',
    'Akpa',
    'Anii',
    'Abinomn',
    'Akpes',
    'Animere',
    'Abishi',
    'Akukem',
    'Anindilyakwa',
    'Abkhaz',
    'Akuku',
    'Aninka',
    'Abom',
    'Akum',
    'Anjam',
    'Ashkun',
    'Abon',
    'Akuntsu',
    'Ankave',
    'Ashtiani',
    'Abron',
    'Akurio',
    'Anmatyerre',
    'Asilulu',
    'Abu',
    'Akwa',
    'Anong',
    'Askopan',
    'Abu’',
    'Al-Sayyid Bedouin Sign Language',
    'Anor',
    'Abua',
    'Alaba-K’abeena',
    'Anserma',
    'Asmat',
    'Abui',
    'Alabama',
    'Ansus',
    'Abun',
    'Alago',
    'Antikarinya',
    'Abure',
    'Alagwa',
    'Anuak',
    'Asoa',
    'Abureni',
    'Alak',
    'Anufo',
    'Assamese',
    'Aceh',
    'Alamblak',
    'Anuki',
    'Assangori',
    'Achagua',
    'Alangan',
    'Anus',
    'Assiniboine',
    'Achang',
    'Alawa',
    'Anuta',
    'Assyrian Neo-Aramaic',
    'Ache',
    'Albanian',
    'Anyin',
    'Asturian',
    'Aché',
    'Albanian Sign Language',
    'Anyin Morofo',
    'Asu',
    'Acheron',
    'Albanian',
    'Aoheng',
    'Asu',
    'Achi',
    'Aore',
    'Asumboa',
    'Acholi',
    'A’ou',
    'Asuri',
    'Achterhoeks',
    'Ap Ma',
    'Asurini of Xingú',
    'Achuar-Shiwiar',
    'Ale',
    'Apache, Jicarilla',
    'Asurini, Tocantins',
    'Achumawi',
    'Alekano',
    'Apache, Kiowa',
    'Ata',
    'Acipa, Eastern',
    'Aleut',
    'Apache, Lipan',
    'Atampaya',
    'Acroá',
    'Aleut, Mednyj',
    'Apache, Mescalero-Chiricahua',
    'Atauran',
    'Adamorobe Sign Language',
    'Algerian Sign Language',
    'Apache, Western',
    'Atayal',
    'Adang',
    'Algonquin',
    'Apal',
    'Ateso',
    'Adangbe',
    'Ali',
    'Apalaí',
    'Athpariya',
    'Adara',
    'Alladian',
    'Apatani',
    'Ati',
    'Adasen',
    'Allar',
    'Apiaká',
    'Atikamekw',
    'Adele',
    'Alngith',
    'Apinayé',
    'Atohwaim',
    'Adi',
    'Alor',
    'Apma',
    'Atong',
    'Adi, Galo',
    'Alta, Northern',
    'Apurinã',
    'Atong',
    'Adioukrou',
    'Alta, Southern',
    'Aputai',
    'Atorada',
    'Adithinngithigh',
    'Altai, Northern',
    'Arabana',
    'Atsam',
    'Adnyamathanha',
    'Altai, Southern',
    'Arabela',
    'Atsugewi',
    'Adonara',
    'Alugu',
    'Arabic',
    'Atta, Faire',
    'Aduge',
    'Alumu-Tesu',
    'Arabic, Algerian Saharan Spoken',
    'Atta, Pamplona',
    'Adyghe',
    'Alune',
    'Arabic, Algerian Spoken',
    'Atta, Pudtol',
    'Adzera',
    'Aluo',
    'Arabic, Baharna Spoken',
    'Attié',
    'Aeka',
    'Alur',
    'Arabic, Chadian Spoken',
    'Au',
    'Aekyom',
    'Alutor',
    'Arabic, Cypriot Spoken',
    '’Auhelawa',
    'Aer',
    'Alviri-Vidari',
    'Arabic, Dhofari Spoken',
    'Aukan',
    'Afade',
    'Alyawarr',
    'Arabic, Eastern Egyptian Bedawi Spoken',
    'Aulua',
    'Afar',
    'Ama',
    'Arabic, Egyptian Spoken',
    'Aurá',
    'Afghan Sign Language',
    'Amahai',
    'Arabic, Gulf Spoken',
    'Aushi',
    'Afitti',
    'Amahuaca',
    'Arabic, Hadrami Spoken',
    'Aushiri',
    'Afrikaans',
    'Amaimon',
    'Arabic, Hijazi Spoken',
    'Auslan',
    'Afro-Seminole Creole',
    'Amako',
    'Arabic, Judeo-Iraqi',
    'Austral',
    'Agarabi',
    'Amal',
    'Arabic, Judeo-Moroccan',
    'Australian Aborigines Sign Language',
    'Agariya',
    'Amam',
    'Arabic, Judeo-Tripolitanian',
    'Austrian Sign Language',
    'Agatu',
    'Amami Koniya Sign Language',
    'Arabic, Judeo-Tunisian',
    'Auwe',
    'Agavotaguerra',
    'Amami-Oshima, Northern',
    'Arabic, Judeo-Yemeni',
    'Auye',
    'Aghem',
    'Amami-Oshima, Southern',
    'Arabic, Libyan Spoken',
    'Avá-Canoeiro',
    'Aghu',
    'Amanayé',
    'Arabic, Mesopotamian Spoken',
    'Avar',
    'Aghu-Tharnggala',
    'Amara',
    'Arabic, Moroccan Spoken',
    'Avatime',
    'Aghul',
    'Amarakaeri',
    'Arabic, Najdi Spoken',
    'Avau',
    'Agi',
    'Amarasi',
    'Arabic, North Levantine Spoken',
    'Avava',
    'Agob',
    'Amazigh',
    'Arabic, North Mesopotamian Spoken',
    'Avestan',
    'Agoi',
    'Amba',
    'Arabic, Omani Spoken',
    'Avikam',
    'Agta, Casiguran Dumagat',
    'Amba',
    'Arabic, Sa’idi Spoken',
    'Avokaya',
    'Agta, Central Cagayan',
    'Ambae, East',
    'Arabic, Sanaani Spoken',
    'Awa',
    'Agta, Dicamay',
    'Ambae, West',
    'Arabic, Shihhi Spoken',
    'Awa',
    'Agta, Dupaninan',
    'Ambai',
    'Arabic, South Levantine Spoken',
    'Awa-Cuaiquer',
    'Agta, Katubung',
    'Ambakich',
    'Arabic, Standard',
    'Awabakal',
    'Agta, Mt. Iraya',
    'Ambel',
    'Arabic, Sudanese Spoken',
    'Awad Bing',
    'Agta, Mt. Iriga',
    'Ambelau',
    'Arabic, Ta’izzi-Adeni Spoken',
    'Awadhi',
    'Agta, Pahanan',
    'Ambele',
    'Arabic, Tajiki Spoken',
    'Awai',
    'Agta, Umiray Dumaget',
    'Amblong',
    'Arabic, Tunisian Spoken',
    'Awajún',
    'Agta, Villa Viciosa',
    'Ambo',
    'Arabic, Uzbeki Spoken',
    'Awak',
    'Aguano',
    'Ambrak',
    'Aragonese',
    'Awakateko',
    'Aguna',
    'Ambrym, North',
    'Araki',
    'Awar',
    'Agutaynen',
    'Ambrym, Southeast',
    'Arakwal',
    'Awara',
    'Agwagwune',
    'Ambul',
    'Aralle-Tabulahan',
    'Awbono',
    'Àhàn',
    'Ambulas',
    'Aramba',
    'Aweer',
    'Ahanta',
    'Amdang',
    'Aranadan',
    'Awera',
    'Aheu',
    'Amele',
    'Aranda, Lower Southern',
    'Awetí',
    'Ahirani',
    'American Sign Language',
    'Arandai',
    'Awing',
    'Ahom',
    'Amharic',
    'Araona',
    'Awishira',
    'Ahtena',
    'Ami',
    'Arapaho',
    'Awiyaana',
    'Ahwai',
    'Amio-Gelimi',
    'Arapaso',
    'Awjilah',
    'Ai-Cham',
    'Amis',
    'Arára, Mato Grosso',
    'Awngi',
    'Aighon',
    'Amo',
    'Arára, Pará',
    'Awngthim',
    'Aikanã',
    'Amol',
    'Ararandewára',
    'Awtuw',
    'Aiklep',
    'Ampanang',
    'Arawak',
    'Awu',
    'Aimaq',
    'Amri Karbi',
    'Araweté',
    'Awun',
    'Aimol',
    'Amto',
    'Arbore',
    'Awutu',
    'Ainbai',
    'Amundava',
    'Archi',
    'Awyi',
    'Ainu',
    'Amurdak',
    'Are',
    'Awyu, Asue',
    'Ainu',
    'Amuzgo, Guerrero',
    '’Are’are',
    'Awyu, Central',
    'Aiome',
    'Amuzgo, Ipalapa',
    'Areba',
    'Awyu, Edera',
    'Airoran',
    'Amuzgo, San Pedro Amuzgos',
    'Arem',
    'Awyu, Jair',
    'Aisi',
    'Anaang',
    'Argentine Sign Language',
    'Awyu, North',
    'Aiton',
    'Anakalangu',
    'Argobba',
    'Awyu, South',
    'Äiwoo',
    'Anal',
    'Arguni',
    'Axamb',
    'Aizi, Aproumu',
    'Anam',
    'Arhâ',
    'Axi',
    'Aizi, Mobumrin',
    'Anambé',
    'Arhö',
    'Ayabadhu',
    'Aizi, Tiagbamrin',
    'Anamuxra',
    'Arhuaco',
    'Ayere',
    'Aja',
    'Anasi',
    'Ari',
    'Ayerrerenge',
    'Aja',
    'Áncá',
    'Aribwatsa',
    'Ayi',
    'Ajawa',
    'Andaandi',
    'Aribwaung',
    'Ayizi',
    'Ajië',
    'Andai',
    'Arigidi',
    'Aymara',
    'Ajiya',
    'Andajin',
    'Arikapú',
    'Aymara, Central',
    'Ajumbu',
    'Andaman Hindi Creole',
    'Arikara',
    'Aymara, Southern',
    'Ajyíninka Apurucayali',
    'Andaqui',
    'Arikem',
    'Ayoreo',
    'Ak',
    'Andarum',
    'Aringa',
    'Ayta, Abellen',
    'Aka',
    'Andegerebinha',
    'Armenian',
    'Ayta, Ambala',
    'Aka-Bea',
    'Andh',
    'Armenian Sign Language',
    'Ayta, Mag-antsi',
    'Aka-Bo',
    'Andi',
    'Armenian, Western',
    'Ayta, Mag-Indi',
    'Aka-Cari',
    'Andio',
    'Aro',
    'Ayta, Magbukun',
    'Aka-Jeru',
    'Andoa',
    'Aromanian',
    'Ayta, Sorsogon',
    'Aka-Kede',
    'Andoque',
    'Arop-Lokep',
    'Ayu',
    'Aka-Kol',
    'Andra-Hus',
    'Arosi',
    'Azerbaijani',
    'Aka-Kora',
    'Aneityum',
    'Arpitan',
    'Azerbaijani, North',
    'Akan',
    'Anem',
    'Arrarnta, Western',
    'Azerbaijani, South',
    'Akar-Bale',
    'Aneme Wake',
    'Arrernte, Eastern',
    'Azha',
    'Akaselem',
    'Anfillo',
    'Arta',
    'Azhe',
    'Akateko',
    'Angaataha',
    'Aruá',
    'Aziana',

    'Baan',
    'Barambu',
    'Biafada',
    'Bontok',
    'Baangi',
    'Baramu',
    'Biage',
    'Bontok, Central',
    'Baatonum',
    'Barapasi',
    'Biak',
    'Bontok, Eastern',
    'Babango',
    'Baras',
    'Biali',
    'Bontok, Northern',
    'Babanki',
    'Barasana-Eduria',
    'Biangai',
    'Bontok, Southern',
    'Babar, North',
    'Barbaram',
    'Biao',
    'Bontok, Southwestern',
    'Babar, Southeast',
    'Barbareño',
    'Biao Mon',
    'Boon',
    'Babatana',
    'Bardi',
    'Biao-Jiao Mien',
    'Boor',
    'Babine',
    'Baré',
    'Biate',
    'Bora',
    'Babuza',
    'Barein',
    'Bibbulman',
    'Borna',
    'Bacama',
    'Bareli, Palya',
    'Bidayuh Serian',
    'Boro',
    'Bada',
    'Bareli, Pauri',
    'Bidayuh, Bau',
    'Borong',
    'Badaga',
    'Bareli, Rathwi',
    'Bidayuh, Biatah',
    'Borôro',
    'Bade',
    'Bargam',
    'Bidayuh, Tringgus-Sembaan',
    'Boruca',
    'Badeshi',
    'Bari',
    'Bidiyo',
    'Boselewa',
    'Badimaya',
    'Barí',
    'Bidjara',
    'Bosmun',
    'Badjiri',
    'Bariai',
    'Bidyogo',
    'Bosnian',
    'Badui',
    'Bariji',
    'Biem',
    'Bote',
    'Badyara',
    'Barikanchi',
    'Bierebo',
    'Botlikh',
    'Baeggu',
    'Barikewa',
    'Bieria',
    'Bouni',
    'Baelelea',
    'Barngarla',
    'Biga',
    'Bouyei',
    'Baetora',
    'Barok',
    'Bigambal',
    'Bozaba',
    'Bafanji',
    'Barombi',
    'Bih',
    'Bozo, Jenaama',
    'Bafaw-Balong',
    'Barrow Point',
    'Bijim',
    'Bozo, Kelengaxo',
    'Bafia',
    'Baruga',
    'Bijori',
    'Bozo, Tiemacèwè',
    'Bafut',
    'Barwe',
    'Bikol',
    'Bozo, Tieyaxo',
    'Baga Kaloum',
    'Barzani-Sandu Jewish Neo-Aramaic',
    'Bikol, Buhi’non',
    'Bragat',
    'Baga Koga',
    'Basa',
    'Bikol, Central',
    'Brahui',
    'Baga Manduri',
    'Basa-Gumna',
    'Bikol, Libon',
    'Braj Bhasha',
    'Baga Pokur',
    'Basa-Gurmana',
    'Bikol, Miraya',
    'Brazilian Sign Language',
    'Baga Sitemu',
    'Basaa',
    'Bikol, Northern Catanduanes',
    'Brem',
    'Baga Sobané',
    'Basap',
    'Bikol, Rinconada',
    'Breri',
    'Bagheli',
    'Basay',
    'Bikol, Southern Catanduanes',
    'Breton',
    'Bagirmi',
    'Bashkardi',
    'Bikol, West Albay',
    'Bribri',
    'Bago-Kusuntu',
    'Bashkort',
    'Bikya',
    'British Sign Language',
    'Bagobo-Klata',
    'Basketo',
    'Bila',
    'Brokkat',
    'Bagri',
    'Basque',
    'Bilakura',
    'Brokpake',
    'Bagupi',
    'Bassa',
    'Bilaspuri',
    'Brokskat',
    'Bagusa',
    'Bassa-Kontagora',
    'Bilba',
    'Broome Pearling Lugger Pidgin',
    'Bagvalal',
    'Bassossi',
    'Bilbil',
    'Bru, Eastern',
    'Baham',
    'Bata',
    'Bilen',
    'Bru, Western',
    'Bahamas English Creole',
    'Batak',
    'Bille',
    'Brunei',
    'Bahau',
    'Batak Alas-Kluet',
    'Bilua',
    'Bu',
    'Bahinemo',
    'Batak Angkola',
    'Bima',
    'Bu',
    'Bahing',
    'Batak Dairi',
    'Bimin',
    'Bua',
    'Bahnar',
    'Batak Karo',
    'Bimoba',
    'Buamu',
    'Bahonsuai',
    'Batak Mandailing',
    'Bina',
    'Buang, Mangga',
    'Bai',
    'Batak Simalungun',
    'Bina',
    'Buang, Mapos',
    'Bai, Central',
    'Batak Toba',
    'Binahari',
    'Bube',
    'Bai, Lama',
    'Batanga',
    'Binandere',
    'Bubi',
    'Bai, Panyi',
    'Batek',
    'Bindal',
    'Bubia',
    'Bai, Southern',
    'Bateri',
    'Bine',
    'Budibud',
    'Baibai',
    'Bathari',
    'Binji',
    'Budong-Budong',
    'Baikeno',
    'Bati',
    'Bintauna',
    'Budu',
    'Baima',
    'Bati',
    'Bintulu',
    'Budukh',
    'Baimak',
    'Batjala',
    'Binukid',
    'Buduma',
    'Bainouk-Gunyaamolo',
    'Bats',
    'Binukidnon, Northern',
    'Budza',
    'Bainouk-Gunyuño',
    'Batu',
    'Binukidnon, Southern',
    'Bugan',
    'Bainouk-Samik',
    'Batui',
    'Binumarien',
    'Bugawac',
    'Baiso',
    'Batuley',
    'Bipi',
    'Bughotu',
    'Baiyamo',
    'Bauchi',
    'Bira',
    'Bugis',
    'Bajan',
    'Bauni',
    'Birao',
    'Buglere',
    'Bajau, Indonesian',
    'Baure',
    'Birgit',
    'Bugun',
    'Bajau, West Coast',
    'Bauria',
    'Birhor',
    'Buhid',
    'Bajelani',
    'Bauwaki',
    'Biri',
    'Buhutu',
    'Baka',
    'Bauzi',
    'Birifor, Malba',
    'Bukat',
    'Baka',
    'Bavarian',
    'Birifor, Southern',
    'Bukharic',
    'Bakairí',
    'Bayali',
    'Biritai',
    'Bukitan',
    'Bakaka',
    'Baybayanon',
    'Birked',
    'Bukiyip',
    'Bakati’',
    'Baygo',
    'Birri',
    'Bukpe',
    'Bakati’, Rara',
    'Bayono',
    'Birrpayi',
    'Buksa',
    'Bakati’, Sara',
    'Bayot',
    'Birwa',
    'Bukusu',
    'Bakhtiâri',
    'Bayungu',
    'Bisã',
    'Bukwen',
    'Baki',
    'Bazigar',
    'Bisa',
    'Bulgarian',
    'Bakoko',
    'Beaver',
    'Bisaya, Brunei',
    'Bulgarian Sign Language',
    'Bakole',
    'Beba',
    'Bisaya, Sabah',
    'Buli',
    'Bakpinka',
    'Bebele',
    'Biseni',
    'Buli',
    'Bakumpai',
    'Bebeli',
    'Bishnupuriya',
    'Bullom So',
    'Bakwé',
    'Bebil',
    'Bishuo',
    'Bulu',
    'Balaesang',
    'Bedamuni',
    'Bisis',
    'Bulu',
    'Balangao',
    'Bedawiyet',
    'Bislama',
    'Bulungan',
    'Balanta-Ganja',
    'Bedjond',
    'Bisorio',
    'Bum',
    'Balanta-Kentohe',
    'Bedoanas',
    'Bisu',
    'Bumaji',
    'Balantak',
    'Beeke',
    'Bit',
    'Bumang',
    'Baldemu',
    'Beele',
    'Bitare',
    'Bumthangkha',
    'Bali',
    'Beembe',
    'Bitur',
    'Bun',
    'Bali',
    'Beezen',
    'Biwat',
    'Buna',
    'Bali',
    'Befang',
    'Biyo',
    'Bunak',
    'Balkan Gagauz Turkish',
    'Beginci',
    'Biyom',
    'Bunama',
    'Balo',
    'Behoa',
    'Blaan, Koronadal',
    'Bundeli',
    'Balochi, Eastern',
    'Bekwarra',
    'Blaan, Sarangani',
    'Bung',
    'Balochi, Southern',
    'Bekwel',
    'Blablanga',
    'Bungain',
    'Balochi, Western',
    'Belait',
    'Blackfoot',
    'Bunganditj',
    'Baloi',
    'Belanda Bor',
    'Blafe',
    'Bungku',
    'Balti',
    'Belanda Viri',
    'Blagar',
    'Bungu',
    'Baluchi',
    'Belarusian',
    'Blang',
    'Bunu, Bu-Nao',
    'Bamali',
    'Belhariya',
    'Bo',
    'Bunu, Jiongnai',
    'Bamanankan',
    'Beli',
    'Bo',
    'Bunu, Wunai',
    'Bambalang',
    'Beli',
    'Bo-Rukul',
    'Bunu, Younuo',
    'Bambam',
    'Belize English Creole',
    'Bo-Ung',
    'Bunuba',
    'Bambili-Bambui',
    'Bella Coola',
    'Boano',
    'Bunun',
    'Bamenyam',
    'Bellari',
    'Boano',
    'Buol',
    'Bamu',
    'Belning',
    'Bobo Madaré, Southern',
    'Bura-Pabir',
    'Bamukumbit',
    'Bemba',
    'Bobongko',
    'Burak',
    'Bamun',
    'Bembe',
    'Bobot',
    'Buraka',
    'Bamunka',
    'Bena',
    'Bodo',
    'Burarra',
    'Bamwe',
    'Bena',
    'Bodo Parja',
    'Burate',
    'Ban Khor Sign Language',
    'Benabena',
    'Bofi',
    'Burduna',
    'Bana',
    'Bench',
    'Boga',
    'Bure',
    'Banam Bay',
    'Bende',
    'Bogaya',
    'Buriat',
    'Banda',
    'Bendi',
    'Boghom',
    'Buriat, China',
    'Banda, Mid-Southern',
    'Beneraf',
    'Bogkalot',
    'Buriat, Mongolia',
    'Banda, South Central',
    'Beng',
    'Boguru',
    'Buriat, Russia',
    'Banda, Togbo-Vara',
    'Benga',
    'Bohtan Neo-Aramaic',
    'Burji',
    'Banda, West Central',
    'Bengali',
    'Boikin',
    'Burmese',
    'Banda-Bambari',
    'Benggoi',
    'Bokha',
    'Burmeso',
    'Banda-Banda',
    'Bentong',
    'Boko',
    'Buru',
    'Banda-Mbrès',
    'Benyadu’',
    'Boko',
    'Buru',
    'Banda-Ndélé',
    'Bepour',
    'Bokobaru',
    'Burui',
    'Banda-Yangere',
    'Berakou',
    'Bokyi',
    'Burumakok',
    'Bandi',
    'Berawan, Central',
    'Bola',
    'Burun',
    'Bandial',
    'Berawan, East',
    'Bolango',
    'Burundian Sign Language',
    'Bandjalang',
    'Berawan, West',
    'Bole',
    'Burunge',
    'Bangala',
    'Berbice Dutch Creole',
    'Bolgo',
    'Burushaski',
    'Bangandu',
    'Berik',
    'Bolia',
    'Burusu',
    'Bangba',
    'Berinomo',
    'Bolinao',
    'Buruwai',
    'Banggai',
    'Berom',
    'Bolivian Sign Language',
    'Busam',
    'Bangi',
    'Berta',
    'Boloki',
    'Busami',
    'Bangime',
    'Berti',
    'Bolon',
    'Bushi',
    'Bangka',
    'Besme',
    'Bolondo',
    'Bushoong',
    'Bangolan',
    'Betaf',
    'Bolyu',
    'Buso',
    'Bangon',
    'Betawi',
    'Bom-Kim',
    'Busoa',
    'Bangubangu',
    'Bete',
    'Boma',
    'Busuu',
    'Bangwinji',
    'Bété, Daloa',
    'Bomboli',
    'Butmas-Tur',
    'Baniva',
    'Bété, Gagnoa',
    'Bomboma',
    'Butuanon',
    'Baniwa',
    'Bété, Guiberoua',
    'Bomitaba',
    'Buwal',
    'Banjar',
    'Bete-Bendi',
    'Bomu',
    'Buyang, Baha',
    'Bankagooma',
    'Beti',
    'Bomwali',
    'Buyang, E’ma',
    'Bankal',
    'Bezhta',
    'Bon Gula',
    'Buyang, Langnian',
    'Bankon',
    'Bhadrawahi',
    'Bonan',
    'Buyu',
    'Bannoni',
    'Bhalay',
    'Bondei',
    'Bwa',
    'Bantawa',
    'Bharia',
    'Bondo',
    'Bwaidoka',
    'Bantayanon',
    'Bhatri',
    'Bonerate',
    'Bwamu, Cwi',
    'Bantik',
    'Bhattiyali',
    'Bonggi',
    'Bwamu, Láá Láá',
    'Bantoanon',
    'Bhaya',
    'Bonggo',
    'Bwanabwana',
    'Banyjima',
    'Bhele',
    'Bongili',
    'Bwatoo',
    'Baoulé',
    'Bhilali',
    'Bongo',
    'Bwela',
    'Barababaraba',
    'Bhili',
    'Bongu',
    'Bwile',
    'Barai',
    'Bhogoto',
    'Bonjo',
    'Bwisi',
    'Barakai',
    'Bhojpuri',
    'Bonkeng',
    'Byangsi',
    'Baram',
    'Bhujel',
    'Bonkiman',
    'Byep',
    'Barama',
    'Bhunjia',

    'Caac',
    'Chatino, Eastern Highland',
    'Chin, Thaiphum',
    'Chungmboko',
    'Cabécar',
    'Chatino, Nopala',
    'Chin, Uppu',
    'Churahi',
    'Cabiyarí',
    'Chatino, Tataltepec',
    'Chin, Zotung',
    'Chut',
    'Cacaopera',
    'Chatino, Western Highland',
    'Chin, Zyphe',
    'Chuukese',
    'Cacua',
    'Chatino, Zacatepec',
    'Chinali',
    'Chuvash',
    'Caddo',
    'Chatino, Zenzontepec',
    'Chinantec, Chiltepec',
    'Chuwabu',
    'Cafundo Creole',
    'Chaudangsi',
    'Chinantec, Comaltepec',
    'Cia-Cia',
    'Cahuarano',
    'Chaura',
    'Chinantec, Lalana',
    'Cicipu',
    'Cahuilla',
    'Chavacano',
    'Chinantec, Lealao',
    'Cimbrian',
    'Cahungwarya',
    'Chechen',
    'Chinantec, Ojitlán',
    'Cineni',
    'Caka',
    'Chehalis, Lower',
    'Chinantec, Ozumacín',
    'Cinta Larga',
    'Cakfem-Mushere',
    'Chehalis, Upper',
    'Chinantec, Palantla',
    'Cishingini',
    'Callawalla',
    'Cheke Holo',
    'Chinantec, Quiotepec',
    'Citak',
    'Caló',
    'Chenapian',
    'Chinantec, Sochiapam',
    'Citak, Tamnim',
    'Caluyanun',
    'Chenchu',
    'Chinantec, Tepetotutla',
    'Ciwogai',
    'Cambodian Sign Language',
    'Chenoua',
    'Chinantec, Tepinapa',
    'Clallam',
    'Camsá',
    'Chepang',
    'Chinantec, Tlacoatzintepec',
    'C’Lela',
    'Camtho',
    'Chepya',
    'Chinantec, Usila',
    'Cochimi',
    'Canela',
    'Cheq Wong',
    'Chinantec, Valle Nacional',
    'Cocopa',
    'Canichana',
    'Cherepon',
    'Chinese',
    'Coeur d’Alene',
    'Cao Lan',
    'Cherokee',
    'Chinese Pidgin English',
    'Cofán',
    'Cao Miao',
    'Chesu',
    'Chinese Sign Language',
    'Col',
    'Capanahua',
    'Chetco',
    'Chinese, Gan',
    'Colombian Sign Language',
    'Capiznon',
    'Chetti, Moundadan',
    'Chinese, Hakka',
    'Columbia-Wenatchi',
    'Cappadocian Greek',
    'Chetti, Wayanad',
    'Chinese, Huizhou',
    'Comanche',
    'Caquinte',
    'Cheyenne',
    'Chinese, Jinyu',
    'Comorian, Maore',
    'Cara',
    'Chhattisgarhi',
    'Chinese, Mandarin',
    'Comorian, Mwali',
    'Carabayo',
    'Chhintang',
    'Chinese, Min Bei',
    'Comorian, Ndzwani',
    'Caramanta',
    'Chhulung',
    'Chinese, Min Dong',
    'Comorian, Ngazidja',
    'Carapana',
    'Chiangmai Sign Language',
    'Chinese, Min Nan',
    'Comox',
    'Carib',
    'Chiapanec',
    'Chinese, Min Zhong',
    'Con',
    'Carijona',
    'Chichewa',
    'Chinese, Pu-Xian',
    'Cook Islands Maori',
    'Carolinian',
    'Chichimeco-Jonaz',
    'Chinese, Wu',
    'Côông',
    'Carrier',
    'Chichonyi-Chidzihana-Chikauma',
    'Chinese, Xiang',
    'Coos',
    'Carrier, Southern',
    'Chickasaw',
    'Chinese, Yue',
    'Coptic',
    'Catalan',
    'Chicomuceltec',
    'Chingoni',
    'Coquille',
    'Catalan Sign Language',
    'Chidigo',
    'Chini',
    'Cora, El Nayar',
    'Catawba',
    'Chiduruma',
    'Chinook',
    'Cora, Santa Teresa',
    'Cavineña',
    'Chiga',
    'Chinook Wawa',
    'Cornish',
    'Cayubaba',
    'Chilcotin',
    'Chipaya',
    'Corsican',
    'Cayuga',
    'Chilean Sign Language',
    'Chippewa',
    'Costa Rican Sign Language',
    'Cebuano',
    'Chilisso',
    'Chiquitano',
    'Cowlitz',
    'Cemuhî',
    'Chimariko',
    'Chiru',
    'Cree',
    'Centúúm',
    'Chimila',
    'Chitimacha',
    'Cree, Moose',
    'Cerma',
    'Chin, Anu-Khongso',
    'Chittagonian',
    'Cree, Northern East',
    'Chachi',
    'Chin, Asho',
    'Chocangacakha',
    'Cree, Plains',
    'Chácobo',
    'Chin, Bawm',
    'Chocholtec',
    'Cree, Southern East',
    'Chadian Sign Language',
    'Chin, Bualkhaw',
    'Choctaw',
    'Cree, Swampy',
    'Chadong',
    'Chin, Daai',
    'Chodri',
    'Cree, Woods',
    'Chagatai',
    'Chin, Eastern Khumi',
    'Chokwe',
    'Crimean Tatar',
    'Chaima',
    'Chin, Ekai',
    'Chol',
    'Croatian',
    'Chak',
    'Chin, Falam',
    'Cholón',
    'Croatian Sign Language',
    'Chakali',
    'Chin, Hakha',
    'Chong',
    'Crow',
    'Chakavian',
    'Chin, Kaang',
    'Choni',
    'Cruzeño',
    'Chakma',
    'Chin, Khumi',
    'Chontal, Highland Oaxaca',
    'Cua',
    'Chala',
    'Chin, Laitu',
    'Chontal, Lowland Oaxaca',
    'Cuban Sign Language',
    'Chaldean Neo-Aramaic',
    'Chin, Lautu',
    'Chontal, Tabasco',
    'Cubeo',
    'Chalikha',
    'Chin, Mara',
    'Chopi',
    'Cuiba',
    'Cham, Eastern',
    'Chin, Matu',
    'Chorote, Iyojwa’ja',
    'Cuicatec, Tepeuxila',
    'Cham, Western',
    'Chin, Müün',
    'Chorote, Iyo’wujwa',
    'Cuicatec, Teutila',
    'Chamacoco',
    'Chin, Ngawn',
    'Ch’orti’',
    'Cuitlatec',
    'Chamalal',
    'Chin, Paite',
    'Chrau',
    'Cumanagoto',
    'Chambeali',
    'Chin, Rawngtu',
    'Chru',
    'Cun',
    'Chambri',
    'Chin, Rungtu',
    'Chuave',
    'Cupeño',
    'Chamicuro',
    'Chin, Senthang',
    'Chug',
    'Curripaco',
    'Chamling',
    'Chin, Siyin',
    'Chuj',
    'Cutchi-Swahili',
    'Chamorro',
    'Chin, Songlai',
    'Chukchi',
    'Cuvok',
    'Changriwa',
    'Chin, Sumtu',
    'Chukwa',
    'Cuyonon',
    'Changthang',
    'Chin, Tawr',
    'Chulym',
    'Czech',
    'Chantyal',
    'Chin, Tedim',
    'Chumburung',
    'Czech Sign Language',
    'Chara',
    'Chin, Thado',
    'Chung',
    'Daakaka',
    'Day',
    'Ding',
    'Dong',
    'Daantanai’',
    'Dayi',
    'Dinka',
    'Dong, Northern',
    'Daasanach',
    'Dazaga',
    'Dinka, Northeastern',
    'Dong, Southern',
    'Daatsʼíin',
    'Deccan',
    'Dinka, Northwestern',
    'Dongo',
    'Daba',
    'Dedua',
    'Dinka, South Central',
    'Dongotono',
    'Dabarre',
    'Defaka',
    'Dinka, Southeastern',
    'Dongxiang',
    'Dabe',
    'Deg',
    'Dinka, Southwestern',
    'Doondo',
    'Dadi Dadi',
    'Deg Xinag',
    'Dirasha',
    'Dorig',
    'Dadibi',
    'Degano',
    'Diri',
    'Dori’o',
    'Dadiya',
    'Degema',
    'Dirim',
    'Doromu-Koki',
    'Daga',
    'Degenang',
    'Disa',
    'Dorze',
    'Dagaare, Southern',
    'Dehwari',
    'Ditammari',
    'Doso',
    'Dagaari Dioula',
    'Dek',
    'Ditidaht',
    'Dotyali',
    'Dagara, Northern',
    'Dela-Oenale',
    'Diuwe',
    'Doutai',
    'Dagba',
    'Delaware',
    'Dixon Reef',
    'Doyayo',
    'Dagbani',
    'Delaware, Pidgin',
    'Diyari',
    'Drehu',
    'Dagik',
    'Delo',
    'Dizin',
    'Drents',
    'Dagoman',
    'Dem',
    'Djabugay',
    'Drubea',
    'Dahalik',
    'Dema',
    'Djabwurrung',
    'Drung',
    'Dahalo',
    'Demisa',
    'Djadjawurrung',
    'Duala',
    'Daho-Doo',
    'Dendi',
    'Djambarrpuyngu',
    'Duano',
    'Dai',
    'Dendi',
    'Djamindjung',
    'Duau',
    'Dair',
    'Dene',
    'Djangun',
    'Dubli',
    'Daju, Dar Daju',
    'Dengese',
    'Djauan',
    'Dubuporo',
    'Daju, Dar Fur',
    'Dengka',
    'Djawi',
    'Dugun',
    'Daju, Dar Sila',
    'Dení',
    'Djeebbana',
    'Duguri',
    'Dakka',
    'Deno',
    'Djinang',
    'Dugwor',
    'Dakota',
    'Denya',
    'Djinba',
    'Duhwa',
    'Dakpakha',
    'Deori',
    'Djiwarli',
    'Duke',
    'Dalabon',
    'Dera',
    'Dla',
    'Dulbu',
    'Dama',
    'Desano',
    'Dobel',
    'Duli-Gey',
    'Damakawa',
    'Desiya',
    'Dobu',
    'Duma',
    'Damal',
    'Dewas Rai',
    'Doe',
    'Dumagat, Remontado',
    'Damar, East',
    'Dewoin',
    'Doga',
    'Dumi',
    'Damar, West',
    'Dezfuli',
    'Doghoro',
    'Dumo',
    'Dambi',
    'Dghwede',
    'Dogon, Ampari',
    'Dumpas',
    'Dameli',
    'Dhaiso',
    'Dogon, Ana Tinga',
    'Dumun',
    'Dampelas',
    'Dhalandji',
    'Dogon, Bankan Tey',
    'Duna',
    'Dan',
    'Dhangu-Djangu',
    'Dogon, Ben Tey',
    'Dungan',
    'Danaru',
    'Dhao',
    'Dogon, Bondum Dom',
    'Dungmali',
    'Danau',
    'Dharawal',
    'Dogon, Bunoge',
    'Dungra Bhil',
    'Dangaléat',
    'Dhargari',
    'Dogon, Dogul Dom',
    'Dungu',
    'Dangi',
    'Dharuk',
    'Dogon, Donno So',
    'Duoluo',
    'Dangme',
    'Dharumbal',
    'Dogon, Jamsay',
    'Dura',
    'Dani, Lower Grand Valley',
    'Dhatki',
    'Dogon, Mombo',
    'Duri',
    'Dani, Mid Grand Valley',
    'Dhimal',
    'Dogon, Nanga Dama',
    'Duriankere',
    'Dani, Upper Grand Valley',
    'Dhimba',
    'Dogon, Tebul Ure',
    'Duruwa',
    'Dani, Western',
    'Dhodia',
    'Dogon, Tene Kan',
    'Dusner',
    'Danish',
    'Dholuo',
    'Dogon, Tiranige Diga',
    'Dusun Deyah',
    'Danish Sign Language',
    'Dhundari',
    'Dogon, Tommo So',
    'Dusun Malang',
    'Dano',
    'Dhungaloo',
    'Dogon, Tomo Kan',
    'Dusun Witu',
    'Danu',
    'Dhurga',
    'Dogon, Toro So',
    'Dutch',
    'Danuwar',
    'Dhuwal',
    'Dogon, Toro Tegu',
    'Duungooma',
    'Dao',
    'Dhuwaya',
    'Dogon, Yanda Dom',
    'Duupa',
    'Daonda',
    'Dia',
    'Dogosé',
    'Duvle',
    'Darai',
    'Dibiyaso',
    'Dogoso',
    'Duwai',
    'Dargwa',
    'Dibo',
    'Dogri',
    'Duwet',
    'Dari',
    'Dibole',
    'Dogri',
    'Duya',
    'Dari, Zoroastrian',
    'Dida, Lakota',
    'Doka',
    'Dwang',
    'Darkinyung',
    'Dida, Yocoboué',
    'Doko-Uyanga',
    'Dyaberdyaber',
    'Darlong',
    'Didinga',
    'Dolgan',
    'Dyan',
    'Darmiya',
    'Dido',
    'Doloman',
    'Dyangadi',
    'Dass',
    'Diebroud',
    'Dolpo',
    'Dyirbal',
    'Datooga',
    'Digaro-Mishmi',
    'Dom',
    'Dyugun',
    'Daungwurrung',
    'Dii',
    'Domaaki',
    'Dza',
    'Daur',
    'Dikaka',
    'Domari',
    'Dzalakha',
    'Davawenyo',
    'Dilling',
    'Dombe',
    'Dzando',
    'Dâw',
    'Dima',
    'Dominican Sign Language',
    'Dzao Min',
    'Dawawa',
    'Dimasa',
    'Dompo',
    'Dzhidi',
    'Dawera-Daweloor',
    'Dimbong',
    'Domu',
    'Dzongkha',
    'Dawida',
    'Dime',
    'Domung',
    'Dzùùngoo',
    'Dawro',
    'Dineor',
    'Dondo',
    'E',
    'Ekegusii',
    'Ende',
    'Ese',
    'Eastern Franconian',
    'Eki',
    'Enets, Forest',
    'Ese Ejja',
    'Ebira',
    'Ekit',
    'Enets, Tundra',
    'Eshtehardi',
    'Ebrié',
    'Ekpeye',
    'Enga',
    'Esimbi',
    'Ebughu',
    'El Hugeirat',
    'Engdewu',
    'Eskayan',
    'Ecuadorian Sign Language',
    'El Molo',
    'Engenni',
    'Esperanto',
    'Ede Cabe',
    'Elege',
    'Enggano',
    'Esselen',
    'Ede Ica',
    'Eleme',
    'English',
    'Essono',
    'Ede Idaca',
    'Elepi',
    'Enlhet',
    'Estonian',
    'Ede Ije',
    'Elip',
    'Enrekang',
    'Estonian Sign Language',
    'Ede Nago, Kura',
    'Elkei',
    'Enu',
    'Estonian, Standard',
    'Edo',
    'Eloyi',
    'Enwan',
    'Etebi',
    'Edolo',
    'Elseng',
    'Enwan',
    'Ethiopian Sign Language',
    'Edopi',
    'Elu',
    'Enxet',
    'Etkywan',
    'Efai',
    'Emae',
    'Enya',
    'Eton',
    'Efate, North',
    'Emai-Iuleha-Ora',
    'Epena',
    'Eton',
    'Efate, South',
    'Eman',
    'Epie',
    'Etsako',
    'Efe',
    'Embaloh',
    'Equatorial Guinean Pidgin',
    'Etulo',
    'Efik',
    'Emberá, Northern',
    'Eravallan',
    'Evant',
    'Efutop',
    'Emberá-Baudó',
    'Ere',
    'Even',
    'Ega',
    'Emberá-Catío',
    'Eritai',
    'Evenki',
    'Eggon',
    'Emberá-Chamí',
    'Erokwanas',
    'Eviya',
    'Egyptian Sign Language',
    'Emberá-Tadó',
    'Erre',
    'Ewage-Notu',
    'Ehueun',
    'Emem',
    'Erromintxela',
    'Éwé',
    'Eibela',
    'Emilian',
    'Ersu',
    'Ewondo',
    'Eitiep',
    'Emplawas',
    'Eruwa',
    'Extremaduran',
    'Ejagham',
    'En',
    'Erzya',
    'Eyak',
    'Ekajuk',
    'E’ñapa Woromaipu',
    'Esahie',
    'Ezaa',
    'Ekari',
    'Enawené-Nawé',
    'Esan',
    'Fa d’Ambu',
    'Fataleka',
    'Flinders Island',
    'Fulah',
    'Fagani',
    'Fataluku',
    'Foau',
    'Fulfulde, Adamawa',
    'Fagauvea',
    'Fayu',
    'Foi',
    'Fulfulde, Bagirmi',
    'Faifi',
    'Fedan',
    'Foia Foia',
    'Fulfulde, Borgu',
    'Faiwol',
    'Fe’fe’',
    'Folopa',
    'Fulfulde, Central-Eastern Niger',
    'Fala',
    'Fembe',
    'Foma',
    'Fulfulde, Maasina',
    'Fali',
    'Feroge',
    'Fon',
    'Fulfulde, Nigerian',
    'Fali of Baissa',
    'Fijian',
    'Fongoro',
    'Fulfulde, Western Niger',
    'Fali, North',
    'Fijian, Western',
    'Foodo',
    'Fuliiru',
    'Fali, South',
    'Filipino',
    'Forak',
    'Fulumu',
    'Fam',
    'Filipino Sign Language',
    'Fordata',
    'Fum',
    'Fanamaket',
    'Finland-Swedish Sign Language',
    'Fore',
    'Fungwa',
    'Fanbak',
    'Finnish',
    'Fortsenal',
    'Fur',
    'Fang',
    'Finnish Sign Language',
    'French',
    'Furu',
    'Fang',
    'Finnish, Kven',
    'French Belgian Sign Language',
    'Futuna, East',
    'Fania',
    'Finongan',
    'French Sign Language',
    'Futuna-Aniwa',
    'Farefare',
    'Fipa',
    'French, Cajun',
    'Fuyug',
    'Faroese',
    'Firan',
    'Frisian',
    'Fwâi',
    'Fars, Northwestern',
    'Fiwaga',
    'Frisian, Northern',
    'Fwe',
    'Fars, Southwestern',
    'Flaaitaal',
    'Friulian',
    'Fyer',
    'Fasu',
    'Flemish Sign Language',
    'Ga',
    'Ga’anda',
    'Ga’dang',
    'Gaa',
    'Gaam',
    'Gabi-Gabi',
    'Gabri',
    'Gadaba, Bodo',
    'Gadaba, Mudhili',
    'Gadaba, Pottangi Ollar',
    'Gadang',
    'Gaddang',
    'Gaddi',
    'Gade',
    'Gadjerawang',
    'Gadsup',
    'Gagadu',
    'Gagauz',
    'Gahri',
    'Gaikundi',
    'Gail',
    'Gaina',
    'Gal',
    'Gala',
    'Galambu',
    'Galela',
    'Galeya',
    'Galice',
    'Galician',
    'Galolen',
    'Gamane',
    'Gambera',
    'Gamilaraay',
    'Gamit',
    'Gamkonora',
    'Gamo-Ningi',
    'Gamo',
    'Gana',
    'Ganang',
    'Ganda',
    'Gane',
    'Ganggalida',
    'Ganglau',
    'Gangte',
    'Gangulu',
    'Gants',
    'Ganza',
    'Ganzi',
    'Gao',
    'Gapapaiwa',
    'Garasia, Adiwasi',
    'Garasia, Rajput',
    'Garhwali',
    'Garifuna',
    'Garig-Ilgar',
    'Garingbal',
    'Garlali',
    'Garo',
    'Garre',
    'Garrwa',
    'Garus',
    'Gata’',
    'Gavak',
    'Gavar',
    'Gavião do Jiparaná',
    'Gavião, Pará',
    'Gawar-Bati',
    'Gawri',
    'Gayil',
    'Gayo',
    'Gazi',
    'Gbagyi',
    'Gban',
    'Gbanu',
    'Gbanziri',
    'Gbari',
    'Gbaya-Bossangoa',
    'Gbaya-Bozoum',
    'Gbaya-Mbodomo',
    'Gbaya, Northwest',
    'Gbaya, Southwest',
    'Gbaya',
    'Gbaya',
    'Gbayi',
    'Gbe, Ayizo',
    'Gbe, Ci',
    'Gbe, Defi',
    'Gbe, Eastern Xwla',
    'Gbe, Gbesi',
    'Gbe, Kotafon',
    'Gbe, Maxi',
    'Gbe, Saxwe',
    'Gbe, Tofin',
    'Gbe, Waci',
    'Gbe, Weme',
    'Gbe, Western Xwla',
    'Gbe, Xwela',
    'Gbii',
    'Gciriku',
    'Ge',
    'Gebe',
    'Gebusi',
    'Gedaged',
    'Gedeo',
    'Geez',
    'Gela',
    'Gelao, Green',
    'Gelao, Red',
    'Geme',
    'Gen',
    'Gende',
    'Gengle',
    'Georgian',
    'Gepo',
    'Gera',
    'Gerai',
    'German Sign Language',
    'German, Colonia Tovar',
    'German, Pennsylvania',
    'German, Standard',
    'German, Swiss',
    'Geruma',
    'Geser-Gorom',
    'Ghadamès',
    'Ghale, Northern',
    'Ghale, Southern',
    'Ghanaian Pidgin English',
    'Ghanaian Sign Language',
    'Ghandruk Sign Language',
    'Ghanongga',
    'Ghari',
    'Ghayavi',
    'Ghera',
    'Ghodoberi',
    'Ghomálá’',
    'Ghomara',
    'Ghotuo',
    'Ghulfan',
    'Gibanawa',
    'Gichuka',
    'Gidar',
    'Giiwo',
    'Gikuyu',
    'Gikyode',
    'Gilaki',
    'Gilima',
    'Gilyak',
    'Gimi',
    'Gimi',
    'Gimme',
    'Gimnime',
    'Ginuman',
    'Ginyanga',
    'Girawa',
    'Girirra',
    'Githabul',
    'Gitua',
    'Gitxsan',
    'Giyug',
    'Giziga, North',
    'Giziga',
    'Gizrra',
    'Glaro-Twabo',
    'Glavda',
    'Glio-Oubi',
    'Gnau',
    'Goaria',
    'Gobu',
    'Godié',
    'Godwari',
    'Goemai',
    'Gofa',
    'Gogo',
    'Gogodala',
    'Gokana',
    'Gola',
    'Golin',
    'Golpa',
    'Gondi, Adilabad',
    'Gondi, Aheri',
    'Gondi, Northern',
    'Gondi',
    'Gone Dau',
    'Gongduk',
    'Gonja',
    'Goodenough, West',
    'Gooniyandi',
    'Gor',
    'Gorakor',
    'Gorap',
    'Goreng',
    'Gorontalo',
    'Gorovu',
    'Gorowa',
    'Goundo',
    'Gourmanchéma',
    'Gowlan',
    'Gowli',
    'Gowro',
    'Gozarkhani',
    'Grangali',
    'Great Andamanese, Mixed',
    'Grebo, Barclayville',
    'Grebo, Central',
    'Grebo, Gboloo',
    'Grebo, Northern',
    'Grebo, Southern',
    'Grebo',
    'Greek Sign Language',
    'Greek, Ancient',
    'Greek',
    'Greenlandic',
    'Grenadian English Creole',
    'Gresi',
    'Groma',
    'Gronings',
    'Gros Ventre',
    'Gua',
    'Guadeloupean French Creole',
    'Guahibo',
    'Guajá',
    'Guajajára',
    'Guambiano',
    'Guana',
    'Guana',
    'Guaraní, Ava',
    'Guaraní, Eastern Bolivian',
    'Guaraní, Mbyá',
    'Guaraní, Paraguayan',
    'Guaraní, Western Bolivian',
    'Guarani',
    'Guarayu',
    'Guarequena',
    'Guatemalan Sign Language',
    'Guató',
    'Guayabero',
    'Gudang',
    'Gudanji',
    'Gude',
    'Gudu',
    'Guduf-Gava',
    'Guébie',
    'Guernésiais',
    'Gugadj',
    'Gugu Badhun',
    'Gugu Warra',
    'Guhu-Samane',
    'Guianese French Creole',
    'Guinea-Bissau Creole',
    'Guinean Sign Language',
    'Guiqiong',
    'Gujarati',
    'Gujari',
    'Gula Iro',
    'Gula',
    'Gula',
    'Gula’alaa',
    'Gulay',
    'Gule',
    'Gumalu',
    'Gumatj',
    'Gumawana',
    'Gumuz',
    'Gun',
    'Gundi',
    'Gunditjmara',
    'Gundungurra',
    'Gungabula',
    'Gungu',
    'Gunwinggu',
    'Gunya',
    'Gupa-Abawa',
    'Gupapuyngu',
    'Guramalum',
    'Gurani',
    'Gurdjar',
    'Gureng Gureng',
    'Gurgula',
    'Gurindji Kriol',
    'Gurindji',
    'Gurmana',
    'Guro',
    'Gurr-goni',
    'Gurung',
    'Guruntum-Mbaaru',
    'Gusilay',
    'Guugu Yimidhirr',
    'Guwa',
    'Guwamu',
    'Guya',
    'Guyanese English Creole',
    'Guyani',
    'Gvoko',
    'Gwa',
    'Gwahatike',
    'Gwak',
    'Gwama',
    'Gwamhi-Wuri',
    'Gwandara',
    'Gweda',
    'Gweno',
    'Gwere',
    'Gwich’in',
    'Gyaazi',
    'Gyalsumdo',
    'Gyele',
    'Gyem',
    'Gyong',
    'Ha',
    'Habun',
    'Hadiyya',
    'Hadza',
    'Haeke',
    'Hahon',
    'Hai|ǁom',
    'Haida, Northern',
    'Haida, Southern',
    'Haida',
    'Haigwai',
    'Haiphong Sign Language',
    'Haisla',
    'Haitian Creole',
    'Haitian Vodoun Culture Language',
    'Haji',
    'Hajong',
    'Hakö',
    'Halang Doan',
    'Halang',
    'Halbi',
    'Halia',
    'Halkomelem',
    'Hamap',
    'Hamba',
    'Hamer-Banna',
    'Hamtai',
    'Han',
    'Hanga Hundi',
    'Hanga',
    'Hangaza',
    'Hani',
    'Hano',
    'Hanoi Sign Language',
    'Hanunoo',
    'Harari',
    'Haroi',
    'Haroti',
    'Harsusi',
    'Haruai',
    'Haruku',
    'Haryanvi',
    'Harzani',
    'Hasha',
    'Hassaniyya',
    'Hatam',
    'Hausa Sign Language',
    'Hausa',
    'Havasupai-Walapai-Yavapai',
    'Haveke',
    'Havu',
    'Hawaii Pidgin',
    'Hawaii Sign Language',
    'Hawaiian',
    'Hawu',
    'Haya',
    'Hazaragi',
    'Hdi',
    'Hebrew, Ancient',
    'Hebrew',
    'Hehe',
    'Heiban',
    'Heiltsuk',
    'Heiyoho',
    'Helong',
    'Hema',
    'Hemba',
    'Herdé',
    'Herero',
    'Hermit',
    'Hértevin',
    'Hewa',
    'Hibito',
    'Hidatsa',
    'Higaonon',
    'Hijuk',
    'Hiligaynon',
    'Himarimã',
    'Hindi, Fiji',
    'Hindi',
    'Hindko, Northern',
    'Hindko, Southern',
    'Hinduri',
    'Hindustani, Sarnami',
    'Hinukh',
    'Hitu',
    'Hiw',
    'Hixkaryána',
    'Hlai',
    'Hlersu',
    'Hmar',
    'Hmong Daw',
    'Hmong Dô',
    'Hmong Don',
    'Hmong Njua',
    'Hmong',
    'Hmwaveke',
    'Ho Chi Minh City Sign Language',
    'Ho-Chunk',
    'Ho',
    'Hoava',
    'Hobyót',
    'Hodï',
    'Hohumono',
    'Hoia Hoia',
    'Holikachuk',
    'Holiya',
    'Holma',
    'Holoholo',
    'Holu',
    'Homa',
    'Honduran Sign Language',
    'Hõne',
    'Hong Kong Sign Language',
    'Honi',
    'Hopi',
    'Horo',
    'Horom',
    'Horpa',
    'Hoti',
    'Hovongan',
    'Hoyahoya',
    'Hozo',
    'Hpon',
    'Hrangkhol',
    'Hre',
    'Hruso',
    'Hu',
    'Huachipaeri',
    'Huarijío',
    'Huastec',
    'Huaulu',
    'Huave, San Dionisio del Mar',
    'Huave, San Francisco del Mar',
    'Huave, San Mateo del Mar',
    'Huave, Santa María del Mar',
    'Huichol',
    'Huilliche',
    'Hukumina',
    'Hulaulá',
    'Huli',
    'Hulung',
    'Humene',
    'Humla',
    'Hunde',
    'Hung',
    'Hungana',
    'Hungarian Sign Language',
    'Hungarian',
    'Hungu',
    'Hunjara-Kaina Ke',
    'Hunsrik',
    'Hunzib',
    'Hupa',
    'Hupdë',
    'Hupla',
    'Hutterisch',
    'Hwana',
    'Hya',
    'Hyam',
    'Hyolmo',
    'I-wak',
    'I’saka',
    'Iaai',
    'Iamalele',
    'Iatê',
    'Iatmul',
    'Iau',
    'Ibaas',
    'Ibaloi',
    'Iban',
    'Ibanag',
    'Ibani',
    'Ibatan',
    'Ibibio',
    'Ibino',
    'Ibu',
    'Ibuoro',
    'Icelandic Sign Language',
    'Icelandic',
    'Iceve-Maci',
    'Ida’an',
    'Idaté',
    'Idere',
    'Idesa',
    'Idi',
    'Idio',
    'Idoma',
    'Idu-Mishmi',
    'Iduna',
    'Ifè',
    'Ifo',
    'Ifugao, Amganad',
    'Ifugao, Batad',
    'Ifugao, Mayoyao',
    'Ifugao, Tuwali',
    'Igala',
    'Igana',
    'Igbo',
    'Igede',
    'Ignaciano',
    'Igo',
    'Iguta',
    'Igwe',
    'Iha Based Pidgin',
    'Iha',
    'Ihievbe',
    'Ijo, Southeast',
    'Ik',
    'Ika',
    'Ikaranggal',
    'Ikizu',
    'Iko',
    'Ikobi',
    'Ikoma-Nata-Isenye',
    'Ikpeng',
    'Ikpeshi',
    'Ikposo',
    'Iku-Gora-Ankwa',
    'Ikulu',
    'Ikwere',
    'Ikwo',
    'Ila',
    'Ile Ape',
    'Ili Turki',
    'Ili’uun',
    'Ilocano',
    'Ilue',
    'Imbongu',
    'Imonda',
    'Imroing',
    'Inabaknon',
    'Inagta Alabat',
    'Inapang',
    'Iñapari',
    'Indian Sign Language',
    'Indo-Portuguese',
    'Indonesian Sign Language',
    'Indonesian, Makassar',
    'Indonesian, Peranakan',
    'Indonesian',
    'Indri',
    'Ineseño',
    'Inga, Jungle',
    'Inga',
    'Ingrian',
    'Ingush',
    'Inku',
    'Innu',
    'Inoke-Yate',
    'Inonhan',
    'Inor',
    'Inter-Zab Jewish Neo-Aramaic',
    'International Sign',
    'Intha',
    'Inuinnaqtun',
    'Inuit Sign Language',
    'Inuktitut, Eastern Canadian',
    'Inuktitut',
    'Inupiaq',
    'Inupiatun, North Alaskan',
    'Inupiatun, Northwest Alaska',
    'Iowa-Oto',
    'Ipiko',
    'Ipili',
    'Ipulo',
    'Iquitu',
    'Ir',
    'Iranian Sign Language',
    'Irántxe',
    'Iranun',
    'Iranun',
    'Iraqw',
    'Irarutu',
    'Iraya',
    'Irish Sign Language',
    'Irish',
    'Irula',
    'Isabi',
    'Isanzu',
    'Isconahua',
    'Isebe',
    'Isekiri',
    'Ishkashimi',
    'Isinay',
    'Isirawa',
    'Islander English Creole',
    'Isnag',
    'Isoko',
    'Israeli Sign Language',
    'Istriot',
    'Isu',
    'Isu',
    'Italian Sign Language',
    'Italian',
    'Itawit',
    'Itelmen',
    'Iten',
    'Itene',
    'Itik',
    'Itneg, Banao',
    'Itneg, Binongan',
    'Itneg, Inlaod',
    'Itneg, Maeng',
    'Itneg, Masadiit',
    'Itneg, Moyadan',
    'Ito',
    'Itonama',
    'Itu Mbon Uzo',
    'Itza’',
    'Iu Mien',
    'Ivatan',
    'Ivbie North-Okpela-Arhe',
    'Iwaidja',
    'Iwal',
    'Iwam, Sepik',
    'Iwam',
    'Ixcatec',
    'Ixil',
    'Iyansi',
    'Iyayu',
    'Iyive',
    'Iyo',
    'Izere',
    'Izii',
    'Izon',
    'Izora',
    'Jabutí',
    'Jad',
    'Jadgali',
    'Jah Hut',
    'Jahanka',
    'Jaitmatang',
    'Jakalteko',
    'Jakattoe',
    'Jakun',
    'Jalkunan',
    'Jamaican English Creole',
    'Jamaican Sign Language',
    'Jamamadí',
    'Jandai',
    'Jandavra',
    'Jangkang',
    'Jangshung',
    'Janji',
    'Japanese Sign Language',
    'Japanese',
    'Japreria',
    'Jaqaru',
    'Jara',
    'Jarai',
    'Jarawa',
    'Jaru',
    'Jaunsari',
    'Javanese, New Caledonian',
    'Javanese, Suriname',
    'Javanese',
    'Javindo',
    'Jawe',
    'Jaya',
    'Jebero',
    'Jeh',
    'Jehai',
    'Jejueo',
    'Jemez',
    'Jere',
    'Jeri Kuo',
    'Jerung',
    'Jewish Babylonian Aramaic',
    'Jhankot Sign Language',
    'Jiamao',
    'Jiarong',
    'Jiba',
    'Jibu',
    'Jiiddu',
    'Jilbe',
    'Jilim',
    'Jimi',
    'Jimjimen',
    'Jina',
    'Jingpho',
    'Jingulu',
    'Jinuo, Buyuan',
    'Jinuo, Youle',
    'Jirel',
    'Jiru',
    'Jita',
    'Jju',
    'Joba',
    'Jofotek-Bromnya',
    'Jogi',
    'Jola-Felupe',
    'Jola-Fonyi',
    'Jola-Kasa',
    'Jonkor Bourmataguil',
    'Jopadhola',
    'Jorá',
    'Jordanian Sign Language',
    'Jowulu',
    'Ju',
    'Juang',
    'Juba Arabic',
    'Judeo-Arabic',
    'Judeo-Berber',
    'Judeo-Georgian',
    'Judeo-Italian',
    'Judeo-Tat',
    'Jukun Takum',
    'Jula',
    'Júma',
    'Jumjum',
    'Jumla Sign Language',
    'Jumli',
    'Jur Modo',
    'Juray',
    'Jurúna',
    'Juwar',
    'Juǀ’hoansi',
    'Jwira-Pepesa',
    'K’iche’',
    'Kaamba',
    'Kaan',
    'Kaansa',
    'Kaapor Sign Language',
    'Kaapor',
    'Kaba Démé, Sara',
    'Kaba Naa, Sara',
    'Kabalai',
    'Kabardian',
    'Kabatei',
    'Kabba',
    'Kabiyè',
    'Kabola',
    'Kaburi',
    'Kabutra',
    'Kabuverdianu',
    'Kabwa',
    'Kabwari',
    'Kacchi',
    'Kachama-Ganjule',
    'Kachari',
    'Kaco’',
    'Kadai',
    'Kadar',
    'Kadaru',
    'Kadazan Dusun',
    'Kadazan, Klias River',
    'Kadazan, Labuk-Kinabatangan',
    'Kadiwéu',
    'Kadu',
    'Kadung',
    'Kaduo',
    'Kaera',
    'Kafa',
    'Kafoa',
    'Kagayanen',
    'Kagoro',
    'Kagulu',
    'Kahe',
    'Kahua',
    'Kaibobo',
    'Kaidipang',
    'Kaiep',
    'Kaikadi',
    'Kaike',
    'Kaiku',
    'Kaili, Da’a',
    'Kaili, Ledo',
    'Kaili, Unde',
    'Kaimbé',
    'Kaimbulawa',
    'Kaingáng, São Paulo',
    'Kaingang',
    'Kairak',
    'Kairiru',
    'Kairui-Midiki',
    'Kais',
    'Kaivi',
    'Kaiwá',
    'Kaiy',
    'Kajakse',
    'Kajali',
    'Kajaman',
    'Kakabai',
    'Kakabe',
    'Kakanda',
    'Kakataibo-Kashibo',
    'Kaki Ae',
    'Kako',
    'Kakwa',
    'Kala Lagaw Ya',
    'Kala',
    'Kalaamaya',
    'Kalabari',
    'Kalabra',
    'Kalagan, Kagan',
    'Kalagan',
    'Kalam',
    'Kalamsé',
    'Kalanadi',
    'Kalanga',
    'Kalanguya',
    'Kalao',
    'Kalapuya',
    'Kalarko',
    'Kalasha',
    'Kalenjin',
    'Kalinga, Butbut',
    'Kalinga, Limos',
    'Kalinga, Lubuagan',
    'Kalinga, Mabaka Valley',
    'Kalinga, Majukayang',
    'Kalinga, Southern',
    'Kalinga, Tanudan',
    'Kalispel-Pend d’Oreille',
    'Kalkoti',
    'Kalkutung',
    'Kallahan, Keley-i',
    'Kalmyk-Oirat',
    'Kalou',
    'Kaluli',
    'Kalumpang',
    'Kam',
    'Kamakan',
    'Kamang',
    'Kamano',
    'Kamantan',
    'Kamar',
    'Kamara',
    'Kamarian',
    'Kamaru',
    'Kamas',
    'Kamasa',
    'Kamasau',
    'Kamayo',
    'Kamayurá',
    'Kamba',
    'Kambaata',
    'Kambera',
    'Kamberau',
    'Kambiwá',
    'Kami',
    'Kami',
    'Kamo',
    'Kamoro',
    'Kamu',
    'Kamuku',
    'Kamula',
    'Kamviri',
    'Kamwe',
    'Kanakanabu',
    'Kanamarí',
    'Kanan',
    'Kanashi',
    'Kanasi',
    'Kanauji',
    'Kandas',
    'Kandawo',
    'Kande',
    'Kandozi-Chapra',
    'Kanembu',
    'Kang',
    'Kanga',
    'Kangean',
    'Kanggape',
    'Kangjia',
    'Kango',
    'Kango',
    'Kangri',
    'Kaniet',
    'Kanikkaran',
    'Kaningi',
    'Kaningra',
    'Kaninuwa',
    'Kanite',
    'Kanjari',
    'Kanju',
    'Kankanaey',
    'Kankanay, Northern',
    'Kannada',
    'Kanoé',
    'Kansa',
    'Kantosi',
    'Kanu',
    'Kanufi',
    'Kanum, Bädi',
    'Kanum, Ngkâlmpw',
    'Kanum, Smärky',
    'Kanum, Sota',
    'Kanuri, Bilma',
    'Kanuri, Manga',
    'Kanuri, Tumari',
    'Kanuri, Yerwa',
    'Kanuri',
    'Kanyok',
    'Kao',
    'Kaonde',
    'Kap',
    'Kapampangan',
    'Kapauri',
    'Kapin',
    'Kapinawá',
    'Kapingamarangi',
    'Kapriman',
    'Kaptiau',
    'Kapya',
    'Kaqchikel-K’iche’ Mixed Language',
    'Kaqchikel',
    'Kara',
    'Kara',
    'Kara',
    'Karaboro, Eastern',
    'Karaboro, Western',
    'Karachay-Balkar',
    'Karagas',
    'Karaim',
    'Karajá',
    'Karajarri',
    'Karakalpak',
    'Karami',
    'Karang',
    'Karanga',
    'Karao',
    'Karas',
    'Karata',
    'Karawa',
    'Karawari',
    'Karbi',
    'Kare',
    'Kare',
    'Karekare',
    'Karelian',
    'Karen, Bwe',
    'Karen, Geba',
    'Karen, Geko',
    'Karen, Mobwa',
    'Karen, Paku',
    'Karen, Phrae Pwo',
    'Karen, Pwo Eastern',
    'Karen, Pwo Northern',
    'Karen, Pwo Western',
    'Karen, S’gaw',
    'Karenggapa',
    'Karey',
    'Kari',
    'Karimjo',
    'Karingani',
    'Karipuna French Creole',
    'Karipuna',
    'Karipúna',
    'Karirí-Xocó',
    'Karitiâna',
    'Kariya',
    'Kariyarra',
    'Karkar-Yuri',
    'Karko',
    'Karnai',
    'Karo',
    'Karo',
    'Karok',
    'Karon Dori',
    'Karon',
    'Karore',
    'Karuwali',
    'Kasabe',
    'Kasanga',
    'Kasem',
    'Kashaya',
    'Kashinawa',
    'Kashkay',
    'Kashmiri',
    'Kashubian',
    'Kasiguranin',
    'Kaska',
    'Kasua',
    'Kata Kolok',
    'Katabagan',
    'Katang, Northern',
    'Katang, Southern',
    'Katawixi',
    'Katcha-Kadugli-Miri',
    'Kâte',
    'Kathu',
    'Kati',
    'Katkari',
    'Katla',
    'Kato',
    'Katso',
    'Katu, Eastern',
    'Katu, Western',
    'Katua',
    'Katukína, Panoan',
    'Katukína',
    'Kaulong',
    'Kaur',
    'Kaure',
    'Kaurna',
    'Kauwera',
    'Kavalan',
    'Kavet',
    'Kawacha',
    'Kawaiisu',
    'Kawe',
    'Kawyaw',
    'Kaxararí',
    'Kaxuiâna',
    'Kayabí',
    'Kayagar',
    'Kayah, Eastern',
    'Kayah, Western',
    'Kayan Mahakam',
    'Kayan, Baram',
    'Kayan, Busang',
    'Kayan, Kayan River',
    'Kayan, Mendalam',
    'Kayan, Rejang',
    'Kayan, Wahau',
    'Kayan',
    'Kayan',
    'Kayapó',
    'Kayardild',
    'Kayaw',
    'Kayeli',
    'Kayong',
    'Kaytetye',
    'Kayupulau',
    'Kazakh',
    'Kazukuru',
    'Ke’o',
    'Keapara',
    'Kebu',
    'Kedang',
    'Keerray-Woorroong',
    'Kehu',
    'Kei',
    'Keiga',
    'Keijar',
    'Kein',
    'Keiyo',
    'Kela',
    'Kelabit',
    'Kele',
    'Kele',
    'Kélé',
    'Keliko',
    'Kelo',
    'Kemak',
    'Kembayan',
    'Kemberano',
    'Kembra',
    'Kemedzung',
    'Kemiehua',
    'Kemtuik',
    'Kendayan',
    'Kendeje',
    'Kendem',
    'Kenga',
    'Keninjal',
    'Kensiu',
    'Kenswei Nsei',
    'Kenyah, Mainstream',
    'Kenyah, Wahau',
    'Kenyan Sign Language',
    'Kenyang',
    'Kenye',
    'Keoru-Ahia',
    'Kepkiriwát',
    'Kepo’',
    'Kera',
    'Kerak',
    'Kereho',
    'Kerek',
    'Keres, Eastern',
    'Keres, Western',
    'Kerewe',
    'Kerewo',
    'Kerinci',
    'Ket',
    'Ketangalan',
    'Kete',
    'Ketengban',
    'Ketum',
    'Kewa, West',
    'Kewapi',
    'Kewat',
    'Keyagana',
    'Kgalagadi',
    'Khah',
    'Khakas',
    'Khalaj',
    'Khaling',
    'Kham, Eastern Parbate',
    'Kham, Gamale',
    'Kham, Sheshi',
    'Kham, Western Parbate',
    'Khamba',
    'Khamti',
    'Khamyang',
    'Khana',
    'Khandesi',
    'Kháng',
    'Khanty',
    'Khao',
    'Kharia Thar',
    'Kharia',
    'Khasi',
    'Khe',
    'Khehek',
    'Khengkha',
    'Khetrani',
    'Khinalugh',
    'Khirwar',
    'Khisa',
    'Khlula',
    'Khmer, Northern',
    'Khmer',
    'Khmu',
    'Kho’ini',
    'Khoekhoe',
    'Kholok',
    'Khorasani Turkish',
    'Khowar',
    'Khua',
    'Khuen',
    'Khün',
    'Khunsari',
    'Khvarshi',
    'Khwedam',
    'Kibaku',
    'Kibala',
    'Kibet',
    'Kibiri',
    'Kickapoo',
    'Kiembu',
    'Kigiryama',
    'Kija',
    'Kikai',
    'Kilivila',
    'Kiliwa',
    'Kilmeri',
    'Kim Mun',
    'Kim',
    'Kimaghima',
    'Kimaragang',
    'Kimbu',
    'Kimbundu',
    'Kimîîru',
    'Kimki',
    'Kimré',
    'Kinabalian',
    'Kinabatangan, Upper',
    'Kinalakna',
    'Kinaray-a',
    'Kinga',
    'Kinnauri, Bhoti',
    'Kinnauri, Chhoyul',
    'Kinnauri, Chitkuli',
    'Kinnauri, Pahari',
    'Kinnauri',
    'Kintaq',
    'Kinuku',
    'Kinyarwanda',
    'Kioko',
    'Kiong',
    'Kiorr',
    'Kiowa',
    'Kipfokomo',
    'Kipsigis',
    'Kiput',
    'Kir-Balar',
    'Kire',
    'Kiribati',
    'Kirike',
    'Kirikiri',
    'Kirya-Konzel',
    'Kis',
    'Kisan',
    'Kisankasa',
    'Kisar',
    'Kisi, Southern',
    'Kisi',
    'Kissi, Northern',
    'Kistane',
    'Kitharaka',
    'Kitsai',
    'Kituba',
    'Kituba',
    'Kiunum',
    'Kiwai, Northeast',
    'Kiwai, Southern',
    'Kiwilwana',
    'Kla-Dan',
    'Klamath-Modoc',
    'Klao',
    'Klon',
    'Ko',
    'Koalib',
    'Koasati',
    'Koba',
    'Kobiana',
    'Kobo',
    'Kobol',
    'Kobon',
    'Kobuka',
    'Koch',
    'Koda',
    'Kodaku',
    'Kodava',
    'Kodeoha',
    'Kodi',
    'Kodia',
    'Kodut, Middle',
    'Kodut, North',
    'Kodut, South',
    'Koenoem',
    'Kofa',
    'Kofei',
    'Kofyar',
    'Kogi',
    'Kohin',
    'Kohistani, Indus',
    'Koho',
    'Koiali, Mountain',
    'Koiari, Grass',
    'Koireng',
    'Koita',
    'Koiwat',
    'Kok Borok',
    'Kok-Nar',
    'Kokata',
    'Koke',
    'Koko Babangk',
    'Koko-Bera',
    'Kokoda',
    'Kokola',
    'Kokota',
    'Kol',
    'Kol',
    'Kol',
    'Kola',
    'Kolami, Northwestern',
    'Kolami, Southeastern',
    'Kolbila',
    'Koli, Kachi',
    'Koli, Parkari',
    'Koli, Wadiyari',
    'Koluwawa',
    'Kom',
    'Kom',
    'Koma',
    'Komba',
    'Kombai',
    'Kombe',
    'Kombio',
    'Komering',
    'Komi-Permyak',
    'Komi-Zyrian',
    'Komi',
    'Kominimung',
    'Komo',
    'Komo',
    'Komodo',
    'Kompane',
    'Komyandaret',
    'Kon Keu',
    'Konabéré',
    'Konai',
    'Konchri Sain',
    'Konda-Dora',
    'Konda',
    'Koneq-koneq',
    'Koneraw',
    'Kongo, San Salvador',
    'Kongo',
    'Konjo, Coastal',
    'Konjo, Highland',
    'Konkani, Goan',
    'Konkani',
    'Konkani',
    'Konkomba',
    'Konni',
    'Kono',
    'Kono',
    'Kono',
    'Konomala',
    'Konongo',
    'Konso',
    'Konzo',
    'Koongo',
    'Koonzime',
    'Koorete',
    'Kopar',
    'Kopkaka',
    'Korafe-Yegha',
    'Koraga, Korra',
    'Koraga, Mudu',
    'Korana',
    'Korandje',
    'Korean Sign Language',
    'Korean',
    'Koreguaje',
    'Koresh-e Rostam',
    'Korku',
    'Korlai Portuguese Creole',
    'Koro Nulu',
    'Koro Wachi',
    'Koro Zuba',
    'Koro',
    'Koro',
    'Koro',
    'Koro',
    'Koromfé',
    'Koromira',
    'Koromu',
    'Koroni',
    'Korop',
    'Koropó',
    'Koroshi',
    'Korowai',
    'Korubo',
    'Korupun-Sela',
    'Korwa',
    'Koryak',
    'Kosare',
    'Kosena',
    'Koshin',
    'Kosraean',
    'Kota Marudu Talantang',
    'Kota',
    'Kota',
    'Koti',
    'Kou',
    'Kouya',
    'Kovai',
    'Kove',
    'Kowaki',
    'Kowiai',
    'Koy Sanjaq Surat',
    'Koya',
    'Koyaga',
    'Koyee',
    'Koyo',
    'Koyukon',
    'Kpagua',
    'Kpala',
    'Kpan',
    'Kpasham',
    'Kpati',
    'Kpatili',
    'Kpeego',
    'Kpelle, Guinea',
    'Kpelle, Liberia',
    'Kpelle',
    'Kpessi',
    'Kplang',
    'Krache',
    'Krahn, Eastern',
    'Krahn, Western',
    'Krahô',
    'Kraol',
    'Krenak',
    'Kreye',
    'Kriang',
    'Krikati-Timbira',
    'Krimchak',
    'Krio',
    'Kriol',
    'Krobu',
    'Krongo',
    'Krumen, Plapo',
    'Krumen, Pye',
    'Krumen, Tepo',
    'Krung',
    'Kryts',
    'Kua-nsi',
    'Kua',
    'Kuamasi',
    'Kuan',
    'Kuanhua',
    'Kuanua',
    'Kuay',
    'Kube',
    'Kubi',
    'Kubo',
    'Kubu',
    'Kuce',
    'Kucong',
    'Kudiya',
    'Kudmali',
    'Kudu-Camo',
    'Kufr Qassem Sign Language',
    'Kugama',
    'Kugbo',
    'Kugu-Muminh',
    'Kuhane',
    'Kui, Dawik',
    'Kui',
    'Kui',
    'Kuijau',
    'Kuikúro-Kalapálo',
    'Kujarge',
    'Kuk',
    'Kukama-Kukamiria',
    'Kukatja',
    'Kuke',
    'Kukele',
    'Kukna',
    'Kuku-Mangk',
    'Kuku-Mu’inh',
    'Kuku-Ugbanh',
    'Kuku-Uwanh',
    'Kuku-Yalanji',
    'Kuku',
    'Kula',
    'Kulango, Bondoukou',
    'Kulango, Bouna',
    'Kulere',
    'Kulfa',
    'Kulina Pano',
    'Kulina',
    'Kulisusu',
    'Kulon-Pazeh',
    'Kulung',
    'Kulung',
    'Kumal',
    'Kumalu',
    'Kumam',
    'Kuman',
    'Kumaoni',
    'Kumarbhag Paharia',
    'Kumba',
    'Kumbainggar',
    'Kumbaran',
    'Kumbewaha',
    'Kumiai',
    'Kumukio',
    'Kumyk',
    'Kumzari',
    'Kuna, Border',
    'Kuna, San Blas',
    'Kunama',
    'Kunbarlang',
    'Kunda',
    'Kundal Shahi',
    'Kunduvadi',
    'Kung-Ekoka',
    'Kung',
    'Kungarakany',
    'Kungardutyi',
    'Kunggari',
    'Kungkari',
    'Kuni-Boazi',
    'Kuni',
    'Kunigami',
    'Kunimaipa',
    'Kunja',
    'Kunjen',
    'Kunyi',
    'Kunza',
    'Kuo',
    'Kuot',
    'Kupa',
    'Kupia',
    'Kupsapiiny',
    'Kur',
    'Kurama',
    'Kuranko',
    'Kurdish, Central',
    'Kurdish, Northern',
    'Kurdish, Southern',
    'Kurdish',
    'Kuri',
    'Kuria',
    'Kurichiya',
    'Kurmukar',
    'Kurnai',
    'Kurrama',
    'Kursav',
    'Kurti',
    'Kurtokha',
    'Kuruáya',
    'Kurudu',
    'Kurumba, Alu',
    'Kurumba, Attapady',
    'Kurumba, Betta',
    'Kurumba, Jennu',
    'Kurumba, Kannada',
    'Kurumba, Mullu',
    'Kurux',
    'Kusaal',
    'Kusaghe',
    'Kushi',
    'Kuskokwim, Upper',
    'Kusu',
    'Kusunda',
    'Kusur-Myet',
    'Kutenai',
    'Kutep',
    'Kuthant',
    'Kutong',
    'Kutto',
    'Kutu',
    'Kuturmi',
    'Kuuk Thayorre',
    'Kuuk-Yak',
    'Kuuku-Ya’u',
    'Kuvale',
    'Kuvi',
    'Kuwaa',
    'Kuwaataay',
    'Kuwema',
    'Kw’adza',
    'Kwa',
    'Kwa’',
    'Kwaami',
    'Kwadi',
    'Kwaio',
    'Kwaja',
    'Kwakum',
    'Kwakwala',
    'Kwambi',
    'Kwamera',
    'Kwami',
    'Kwandu',
    'Kwang',
    'Kwanga',
    'Kwangali',
    'Kwanja',
    'Kwara’ae',
    'Kwasio',
    'Kwaya',
    'Kwaza',
    'Kwegu',
    'Kwer',
    'Kwerba Mamberamo',
    'Kwerba',
    'Kwere',
    'Kwerisa',
    'Kwese',
    'Kwesten',
    'Kwini',
    'Kwinsu',
    'Kwinti',
    'Kwoma',
    'Kwomtari',
    'Kyak',
    'Kyaka',
    'Kyanga',
    'Kyenele',
    'Kyerung',
    'Kyoli',
    'Kyrgyz'
];

